apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque # indicates this is the generic secret
data:
  DB_NAME: "Y3VzdG9tZXJz" # echo -n "customers" | base64, here -n refers to - no trailing newline
  USERNAME: "cm9vdA=="
  PASSWORD: "YWRtaW4xMjM="